CREATE TABLE [dbo].[Location]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(MAX) NOT NULL,
	[Code] NVARCHAR(MAX) NOT NULL,
	[Active] BIT NOT NULL DEFAULT 1,
	[CreatedOn]			DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
)